title: Luce in altis
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://kmu.hwstage.com
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: hwstage
  email: hwstage@kookmin.ac.kr

google_analytics: "UA-58263416-1"

comment:
  provider: "disqus"
  disqus:
    shortname: "hwstage"
